server:
  port: 8080

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      base-path: /